### PR TITLE
Add TensorBoard TEXT configuration and better implementation of gradient capture

### PR DESCRIPTION
**Pull request by Mazecreator**
This will close https://github.com/reinforceio/tensorforce/pull/233 as there is a better implementation pushing the summary capture into the Optimizer class

Added feature of capturing Metaparameter from "Agent" and populating the TensorBoard TEXT screen with that configuration data for rapid review.  Custom Dictionary data can be include to populate into TensorBoard.

        metaparams['MyDescription'] = "This experiment covers the first test ...."
        metaparams['My2D'] = np.ones((9,9))   # 9x9 matrix of  1.0's
        metaparams['My1D'] = np.ones((9))   # Column of 9   1.0's

        summary_spec=dict(directory=CkptDir, meta_dict=metaparams, steps=50,labels=['print_configuration','configuration','gradients']),      

labels: 
  * print_configuration - outputs configuration data to STDOUT
  * configuration - populates TensorBoard TEXT panel with configuration data
  * gradients - captures gradient data from training

### CODE REVIEW

**Comment by michaelschaarschmidt** [comment]
Hey,

thanks for this, a few comments to begin with to prepare a merge:
- Line comments typically over the line not at the end of the line in our code 
- In particular there are quite a few overly long line comments, we try to observe max lengths 100-120

**Comment by Mazecreator** [comment]
No problem, I cleaned up the comments.

**Comment by Mazecreator** [comment]
Latest commit removes duplicate code and adds MEAN & VARIANCE scalar gradient summaries.

**Comment by michaelschaarschmidt** [comment]
Thank you,

a few more comments:

```    def ConvertNDArrayToMD(self,data,format_type=0,eol=None):```

- non-static methods should not be capitalised to avoid misunderstandings
- spacing should be pep8 compliant, i.e. spaces after comma-separated arguments ```self, data, x```

**Comment by Mazecreator** [comment]
Okay, I will update that, looks like a few conflicting files now as well.  Do you want me to update the staticmethods in those files and chase down the any broken links:

    @staticmethod
    def from_spec(spec, kwargs=None):

seems like this should be "FromSpec"?

**Comment by michaelschaarschmidt** [comment]
Sorry the non-static was a mixup, we don't capitalise static either, and no camel-case, always underscore, we camel case class names and generally aim to follow:
https://google.github.io/styleguide/pyguide.html?showone=Naming#Naming

**Comment by Mazecreator** [comment]
Closing due to new conflicts, new clean pull request submitted with requested changes.

**Comment by AlexKuhnle** [comment]
One additional comment: Could you make the arguments [here](https://github.com/reinforceio/tensorforce/pull/250/commits/6dcc60536df2a046f72faa94b52b5cc2f631a25c#diff-12aa0668d288202fb1bef17c18f6b76aR34) explicit, like e.g. [here](https://github.com/reinforceio/tensorforce/blob/master/tensorforce/core/networks/layer.py#L38), instead of using `**kwargs`? I have to look into [this part](https://github.com/reinforceio/tensorforce/pull/250/commits/6dcc60536df2a046f72faa94b52b5cc2f631a25c#diff-7e3f4e6f7ac8c85dfed66ccf8e458e03R881) as well (summaries are integrated via the summary hook, so shouldn't be necessary to call them explicitly), but can do that after the merge and adapt things if necessary.

**Pull request closed without merging**
