### PR TITLE
Implementation of parallel evaluation of actions and observations

### PR DESCRIPTION
**Pull request by Deathn0t**
Corresponding to the execution config (with num_parallel) of an agent :
Tested with PPOagent, with num_parallel=1 and num_parallel=2, and with update_mode(batch_size=1, frequency=1) and update_mode(batch_size=10, frequency=10)
```
execution=dict(
            type='single',
            num_parallel=2,
            session_config=None,
            distributed_spec=None)
```

### CODE REVIEW

**Comment by AlexKuhnle** [comment]
Hey @Deathn0t, thanks very much for contributing this feature. Looks all good!

**Comment by sam-ngu** [comment]
Hi, thanks a lot for this feature!
I noticed there is an issue in 'parallel_runner.py' line 137
``` python 

                self.episode_actions.append(self.environment.conv_action)
```
Correct me if I'm wrong, but as far as i know, the environment class does not have the conv_action property. 

What does conv_action stand for? I'm guessing you are trying to keep track of all the actions taken by the agent in the current episode?

**Comment by AlexKuhnle** [comment]
Hey @sam-ngu, letting @Deathn0t answer the specific question, but just to let you know that there is a new version coming which you can find under the `major-revision` branch. There are a few API changes, like `num_parallel` is called `parallel_interactions` and is a high-level argument, but it also supports an updated `parallel_runner` feature ([see here](https://github.com/tensorforce/tensorforce/blob/major-revision/tensorforce/execution/parallel_runner.py)). So you may consider switching, and happy to answer porting questions e.g. on Gitter.

**Comment by sam-ngu** [comment]
@AlexKuhnle Thanks a lot for the info! Will check it out.

**Comment by Deathn0t** [comment]
Hi @sam-ngu , you're right this is a mistake ! I was using a specific environment which was having this `conv_action` attribute that's why!

**Pull request merged**
