### PR TITLE
add summary_spec for 'inputs' show states,actions,rewards

### PR DESCRIPTION
**Pull request by Mazecreator**
This adds histograms for the States, Actions, and reward input values if "inputs" is added to the labels of the summary_specs

screenshot 2017-11-09 16 37 35

### CODE REVIEW

**Comment by Mazecreator** [comment]
I have an update for this to include "regularization" details, but I can't get the L1/L2 data into my DQN to test it.  I can push it if you would like as it catches the "entropy" but that seems to be the only value returned.

**Comment by Mazecreator** [comment]
I did add "regularization" as well that might help debugging or investigating issues.

**Comment by Mazecreator** [comment]
Found the issue with the missing L2/L1 regularization, new pull request submitted

**Comment by AlexKuhnle** [comment]
Thankt @Mazecreator!

**Pull request merged**
