### PR TITLE
(for consideration) Conv2d: allow separate width/height values for window, stride

### PR DESCRIPTION
**Pull request by lefnire**
Allows having different width than height (for non-square windows) in Conv2D

### CODE REVIEW

**Comment by tms1337** [comment]
#153

**Comment by lefnire** [comment]
sorry @tms1337 totally missed that! I'll leave this open since it's for #dev branch

**Comment by AlexKuhnle** [comment]
Thanks both @tms1337  and @lefnire. I merged this one now, since it's on dev, and both PRs are essentially the same. :+1:

**Comment by lefnire** [comment]
sorry I stole your kill @tms1337

**Comment by tms1337** [comment]
@lefnire haha no prob

**Pull request merged**
