### PR TITLE
Learnable Beta plus a few more TF activation functions

### PR DESCRIPTION
**Pull request by Mazecreator**
Added swish activation as well as learnable Beta.  Beta parameter can also be added as a constant through the new "activation_kwargs".  A few new TF activations added:
lrelu/leaky_relu: kwargs 'alpha' can be set for leaky slope
crelu
softsign

kwargs supports the follow:
                        {'beta': float|int|'learn'} # for beta factor on input
                        {'alpha': float|int}   # For leaky Relu
                        {'max': float|int}   # Clip maximum input to activation at "max"
                        {'min': float|int}   # Clip minimum input to activation at "min"

min/max have been added to clip the input values.  So for example, if you want a tf.nn.relu6, use a relu with a {'max': 6.0}.

New summary_labels 'beta' will show a scalar graph in tensorflow of the learned beta parameter.

### CODE REVIEW

**Comment by Mazecreator** [comment]
Reworked activation definition:
dict(type='dense', size=15, activation={'name':'swish', 'beta': 1.9} )
dict(type='dense', size=15, activation={'name':'swish' ,'beta': 'learn'} )
dict(type='dense', size=10, activation={'name':'leaky_relu', 'max': 10.0, 'alpha': 0.31}
dict(type='dense', size=10, activation={'name':'lrelu', 'max': 10.0, 'min':-10.0} )

**Comment by AlexKuhnle** [comment]
Hi @Mazecreator,

First, two details: We always want operator spacing (for `*` in your code) and named arguments for Tensorflow functions (`tf.minimum` etc in your code). Second, I would definitely not use `kwargs` as parameter to `Nonlinearity`, but instead spell all the arguments out and pass `activation` in e.g. `Dense` via `**activation`. Third, I'm thinking whether these `min` and `max` values should really be a separate layer `clip_value` or so. Fourth, is the multiplication with `self.beta` really what you want here: `x = tf.minimum((self.beta*x), self.max)`?

**Comment by Mazecreator** [comment]
@AlexKuhnle I will try to get to this over the weekend as I have a few other things to accomplish ahead of this one.  I think I understand what you are saying here so "self.beta * x", and x = tf.minimum(x=(self.beta * x), y=self.max).

I think the min/max should also be a layer but also belong as part of the activation.  The inspiration for this addition is "relu6".  I didn't want to add an arbitrary upper clipping of 6, so to make this you would use a relu with a max of 6 (you can change it to 7 or whatever now).  The min is there in case there is desire to explore in this area too.  I think adding another layer feels like another layer not an activation function.  But I do believe there are times for clarity, a new layer would be a better approach.  It certainly would add flexibility.

As for the forth point... I am open to suggestions... My thought was if we were to put in a "relu6" for example but beta is 2.0, then setting a max of 6 would clip a value of 3.0 * 2.  If the beta is not there, then the clipping would actually be at 12.0.  I am flexible on this, that was my thinking, but not sure it is a perfect reasoning.  I was simply considering the input as (X * BETA), this might not be appropriate for more complex activation functions such as elu(), etc...  Here, a separate layer would not be able to handle this situation if beta is trainable.

**Comment by AlexKuhnle** [comment]
Okay, we can definitely leave `min` and `max` as they are for now (could still change it later, if we wanted). I'm also not sure re the last point, I just thought it's not what I would have expected as behavior to multiply twice with `beta` if `min` or `max` are set, and I think it is indeed not quite what one wants, right? Other than that, happy to merge after the other 1-2 minor corrections, thanks!

**Comment by Mazecreator** [comment]
@AlexKuhnle I was hoping to avoid a lot of overhead in layers without a Nonlinearity.  By passing hard parameters in the INIT it is going to be tricky to handle the backward compatibility for the "type='relu'" for example.  I need to check in each impacted layer if the type is a dict or string.  And figure if it is a string, make it an activation['name'] value to pass into the Nonlinearity.  Is this your expectation or show I maybe create a UTIL which does just this function?

**Comment by AlexKuhnle** [comment]
Hmm, let me check what exactly it would look like, and probably we can just merge the PR and later on improve this bit, if we want. What I mean is a general mechanism as we have for specs generally, where it's possible to say `optimizer='adam'`  or `optimizer=dict(type='adam', ...)`. It seems a good idea for layers to allow shallow and detailed configurability for sub-layers of more complex layers without argument overhead. If it's a good idea, no need to worry too much about backward compatibility (we're still early alpha :-).

**Comment by Mazecreator** [comment]
I do like the backward compatibility so we don't break all older networks.  I think we can do it, but to eliminate the redundant code I will create a utility to make the conversion "prepare_activation()".  This will allow the activation to be handled the same way as the optimizer.  A more generic version of that utility might be handy to cover other cases if there are any in the future.  But for now, I will make it specifically for the Activation.

**Comment by Mazecreator** [comment]
Made the conversions for the hard params and pep8.  Added a util to prepare kwargs to eliminate redundant code but support passing string or dict into activation parameter.

**Comment by michaelschaarschmidt** [comment]
Hey, looks like there are some build problems with this:
'    from tensorforce.core.networks.layer import Layer, Nonlinearity, Dropout, Flatten, Pool2d, Embedding, Linear, Dense, \
E     File "/tensorforce/tensorforce/core/networks/layer.py", line 624
E       self.nonlinearity = Nonlinearity(**util.prepare_kwargs(activation), summary_labels=summary_labels)
E                                                                         ^
E   SyntaxError: invalid syntax'

**Comment by Mazecreator** [comment]
@michaelschaarschmidt any idea what the issue is here?  I can't tell which Python version threw this error.  The code is fine on 3.5 as this is simply a (**activation) where activation is a function that returns a dictionary.  I can try moving the ** to the end of the function call?  Not sure if this is a 2.7 error or not?

**Comment by michaelschaarschmidt** [comment]
Don't really know, sorry, are you using PyCharm or similar? That should give you the relevant compatibility warnings and hints

**Comment by Mazecreator** [comment]
I don't have PyCharm... 

At this point if you think this is going to break other Python versions, I would request if you can delete/reject the https://github.com/reinforceio/tensorforce/pull/298/commits/07f2ef70de1c30c687cdfb7951ff197daceb5e96 commit and commit it as originally proposed.  We can figure out the kwargs later.  I don't have a way to debug this issue as it doesn't fail on my system.  We could also ask if there are others out there that might be able to test 2.7 and 3.6 with this commit and give feedback of what may be the problem.  Ultimately, this is simply a **kwargs argument only with a function rather than kwargs.

**Comment by AlexKuhnle** [comment]
I think swapping the arguments is what needs to be done. If I remember correctly, `**` arguments should always be after specified named arguments.

**Comment by michaelschaarschmidt** [comment]
Just wanted to add that there is a pycharm community edition, and it is really worth it for debugging and the hinting

**Comment by Mazecreator** [comment]
I will look into a pycham, I use Visual Studio Code now.  I will swap the two params and give that a shot.

**Comment by lefnire** [comment]
@Mazecreator is this by default the same as before, if we don't change/use any of the new args? (ie,  will pulling this commit not change anything out of the box?)

**Comment by Mazecreator** [comment]
@lefnire this commit should be total backward compatible and not impact any prior networks/results.

The recommended use for Swish is with no arguments or if you dare with the "learn" argument for beta.

**Pull request merged**
