### PR TITLE
DQN & Threaded fixes

### PR DESCRIPTION
**Pull request by Islandman93**
- Creates distributions for target networks in Q Models so that the final layers are not shared
- Fixes WorkerAgent -> WorkerAgentGenerator, worker agents need to inherit from the desired Agent class otherwise they will never update the model.
- Multithreaded summaries, needed to modify def after_run(self, run_context, run_values): in the SummarySaverHook to check if the fetches included summaries instead of using it's internal variable since individual threads will overwrite that flag. Essentially the summaries would be computed but not written, now they are always written if computed.

### CODE REVIEW

**Comment by Islandman93** [comment]
Looks like the test is failing on the multi action output. This is because network.get_variables() is returning duplicates.

### Example failing (dqn multi action)
```
=== Source Vars ===
<tf.Variable 'actions-and-internals/apply/apply/apply/W:0' shape=(2, 32) dtype=float32_ref>
<tf.Variable 'actions-and-internals/apply/apply/apply/b:0' shape=(32,) dtype=float32_ref>
<tf.Variable 'actions-and-internals/apply/apply_1/apply/W:0' shape=(32, 32) dtype=float32_ref>
<tf.Variable 'actions-and-internals/apply/apply_1/apply/b:0' shape=(32,) dtype=float32_ref>
<tf.Variable 'actions-and-internals/apply/apply_2/apply/W:0' shape=(2, 32) dtype=float32_ref>
<tf.Variable 'actions-and-internals/apply/apply_2/apply/b:0' shape=(32,) dtype=float32_ref>
<tf.Variable 'actions-and-internals/apply/apply_3/apply/W:0' shape=(32, 32) dtype=float32_ref>
<tf.Variable 'actions-and-internals/apply/apply_3/apply/b:0' shape=(32,) dtype=float32_ref>
<tf.Variable 'actions-and-internals/apply/apply/apply/W:0' shape=(2, 32) dtype=float32_ref>
<tf.Variable 'actions-and-internals/apply/apply/apply/b:0' shape=(32,) dtype=float32_ref>
<tf.Variable 'actions-and-internals/apply/apply_1/apply/W:0' shape=(32, 32) dtype=float32_ref>
<tf.Variable 'actions-and-internals/apply/apply_1/apply/b:0' shape=(32,) dtype=float32_ref>
<tf.Variable 'actions-and-internals/apply/apply_2/apply/W:0' shape=(2, 32) dtype=float32_ref>
<tf.Variable 'actions-and-internals/apply/apply_2/apply/b:0' shape=(32,) dtype=float32_ref>
<tf.Variable 'actions-and-internals/apply/apply_3/apply/W:0' shape=(32, 32) dtype=float32_ref>
<tf.Variable 'actions-and-internals/apply/apply_3/apply/b:0' shape=(32,) dtype=float32_ref>
<tf.Variable 'actions-and-internals/apply/apply/apply/W:0' shape=(2, 32) dtype=float32_ref>
<tf.Variable 'actions-and-internals/apply/apply/apply/b:0' shape=(32,) dtype=float32_ref>
<tf.Variable 'actions-and-internals/apply/apply_1/apply/W:0' shape=(32, 32) dtype=float32_ref>
<tf.Variable 'actions-and-internals/apply/apply_1/apply/b:0' shape=(32,) dtype=float32_ref>
<tf.Variable 'actions-and-internals/apply/apply_2/apply/W:0' shape=(2, 32) dtype=float32_ref>
<tf.Variable 'actions-and-internals/apply/apply_2/apply/b:0' shape=(32,) dtype=float32_ref>
<tf.Variable 'actions-and-internals/apply/apply_3/apply/W:0' shape=(32, 32) dtype=float32_ref>
<tf.Variable 'actions-and-internals/apply/apply_3/apply/b:0' shape=(32,) dtype=float32_ref>
<tf.Variable 'actions-and-internals/apply/apply/apply/W:0' shape=(2, 32) dtype=float32_ref>
<tf.Variable 'actions-and-internals/apply/apply/apply/b:0' shape=(32,) dtype=float32_ref>
<tf.Variable 'actions-and-internals/apply/apply_1/apply/W:0' shape=(32, 32) dtype=float32_ref>
<tf.Variable 'actions-and-internals/apply/apply_1/apply/b:0' shape=(32,) dtype=float32_ref>
<tf.Variable 'actions-and-internals/apply/apply_2/apply/W:0' shape=(2, 32) dtype=float32_ref>
<tf.Variable 'actions-and-internals/apply/apply_2/apply/b:0' shape=(32,) dtype=float32_ref>
<tf.Variable 'actions-and-internals/apply/apply_3/apply/W:0' shape=(32, 32) dtype=float32_ref>
<tf.Variable 'actions-and-internals/apply/apply_3/apply/b:0' shape=(32,) dtype=float32_ref>
<tf.Variable 'actions-and-internals/parameterize/apply/W:0' shape=(32, 1) dtype=float32_ref>
<tf.Variable 'actions-and-internals/parameterize/apply/b:0' shape=(1,) dtype=float32_ref>
<tf.Variable 'actions-and-internals/parameterize_1/apply/W:0' shape=(32, 4) dtype=float32_ref>
<tf.Variable 'actions-and-internals/parameterize_1/apply/b:0' shape=(4,) dtype=float32_ref>
=== Target Vars ===
<tf.Variable 'loss-per-instance/apply/apply/apply/W:0' shape=(2, 32) dtype=float32_ref>
<tf.Variable 'loss-per-instance/apply/apply/apply/b:0' shape=(32,) dtype=float32_ref>
<tf.Variable 'loss-per-instance/apply/apply_1/apply/W:0' shape=(32, 32) dtype=float32_ref>
<tf.Variable 'loss-per-instance/apply/apply_1/apply/b:0' shape=(32,) dtype=float32_ref>
<tf.Variable 'loss-per-instance/apply/apply_2/apply/W:0' shape=(2, 32) dtype=float32_ref>
<tf.Variable 'loss-per-instance/apply/apply_2/apply/b:0' shape=(32,) dtype=float32_ref>
<tf.Variable 'loss-per-instance/apply/apply_3/apply/W:0' shape=(32, 32) dtype=float32_ref>
<tf.Variable 'loss-per-instance/apply/apply_3/apply/b:0' shape=(32,) dtype=float32_ref>
<tf.Variable 'loss-per-instance/apply/apply/apply/W:0' shape=(2, 32) dtype=float32_ref>
<tf.Variable 'loss-per-instance/apply/apply/apply/b:0' shape=(32,) dtype=float32_ref>
<tf.Variable 'loss-per-instance/apply/apply_1/apply/W:0' shape=(32, 32) dtype=float32_ref>
<tf.Variable 'loss-per-instance/apply/apply_1/apply/b:0' shape=(32,) dtype=float32_ref>
<tf.Variable 'loss-per-instance/apply/apply_2/apply/W:0' shape=(2, 32) dtype=float32_ref>
<tf.Variable 'loss-per-instance/apply/apply_2/apply/b:0' shape=(32,) dtype=float32_ref>
<tf.Variable 'loss-per-instance/apply/apply_3/apply/W:0' shape=(32, 32) dtype=float32_ref>
<tf.Variable 'loss-per-instance/apply/apply_3/apply/b:0' shape=(32,) dtype=float32_ref>
<tf.Variable 'loss-per-instance/parameterize/apply/W:0' shape=(32, 1) dtype=float32_ref>
<tf.Variable 'loss-per-instance/parameterize/apply/b:0' shape=(1,) dtype=float32_ref>
<tf.Variable 'loss-per-instance/parameterize_1/apply/W:0' shape=(32, 4) dtype=float32_ref>
<tf.Variable 'loss-per-instance/parameterize_1/apply/b:0' shape=(4,) dtype=float32_ref>
```

### Example working, dqn without multi actions
```
=== Source Vars ===
<tf.Variable 'actions-and-internals/apply/apply/apply/W:0' shape=(2, 32) dtype=float32_ref>
<tf.Variable 'actions-and-internals/apply/apply/apply/b:0' shape=(32,) dtype=float32_ref>
<tf.Variable 'actions-and-internals/apply/apply_1/apply/W:0' shape=(32, 32) dtype=float32_ref>
<tf.Variable 'actions-and-internals/apply/apply_1/apply/b:0' shape=(32,) dtype=float32_ref>
<tf.Variable 'actions-and-internals/apply/apply_2/lstm_cell/bias:0' shape=(128,) dtype=float32_ref>
<tf.Variable 'actions-and-internals/apply/apply_2/lstm_cell/kernel:0' shape=(64, 128) dtype=float32_ref>
<tf.Variable 'actions-and-internals/parameterize/apply/W:0' shape=(32, 2) dtype=float32_ref>
<tf.Variable 'actions-and-internals/parameterize/apply/b:0' shape=(2,) dtype=float32_ref>
=== Target Vars ===
<tf.Variable 'loss-per-instance/apply/apply/apply/W:0' shape=(2, 32) dtype=float32_ref>
<tf.Variable 'loss-per-instance/apply/apply/apply/b:0' shape=(32,) dtype=float32_ref>
<tf.Variable 'loss-per-instance/apply/apply_1/apply/W:0' shape=(32, 32) dtype=float32_ref>
<tf.Variable 'loss-per-instance/apply/apply_1/apply/b:0' shape=(32,) dtype=float32_ref>
<tf.Variable 'loss-per-instance/apply/apply_2/lstm_cell/bias:0' shape=(128,) dtype=float32_ref>
<tf.Variable 'loss-per-instance/apply/apply_2/lstm_cell/kernel:0' shape=(64, 128) dtype=float32_ref>
<tf.Variable 'loss-per-instance/parameterize/apply/W:0' shape=(32, 2) dtype=float32_ref>
<tf.Variable 'loss-per-instance/parameterize/apply/b:0' shape=(2,) dtype=float32_ref>
```

## Code to reproduce
``` python
# after line 152 in this branch
print('=== Source Vars ===')
[print(x) for x in self.network.get_variables() + network_distributions_variables]
print('=== Target Vars ===')
[print(x) for x in self.target_network.get_variables() + target_distributions_variables]
```

**Comment by AlexKuhnle** [comment]
Thanks for spotting the variables issue, this is of course a serious bug. I have fixed it and will commit soon.

**Comment by AlexKuhnle** [comment]
Pushed this change now.

**Comment by AlexKuhnle** [comment]
One question and one request:
- Why do you (re)implement the `after_run` for `UpdateSummarySaverHook`? As far as I can tell, the functionality essentially doesn't change...
- Could you remove the static methods `get_distributions_variables` and `get_distributions_summaries`, and duplicate the code instead? Makes it more consistent to the rest of the library (we never really use static methods), for now.

**Comment by Islandman93** [comment]
- The tensorflow default doesn't take into account a multi-threaded environment. The problem is on this [line](https://github.com/tensorflow/tensorflow/blob/r1.4/tensorflow/python/training/basic_session_run_hooks.py#L662). Where after_run checks to see if self._request_summary is true. But in a multithreaded environment another thread can already have set self._request_summary to false (for instance if it called model.act() or anything other than update). So what happens is the summaries are computed (they are added to the fetches in before_run) but never written since the self._request_summary flag is false by the time the session.run call finishes. My change simply checks to see if summaries were requested by seeing if they are in the fetches.
- I could move them into just class methods if you prefer? The problem with duplicate code is it reduces the modularity of the code base. For example, if someone wanted to create a model that inherits from q_model but has a custom distribution they would have to modify the q_model file instead of their own. In fact (if duplicated), they'd have to do this in two places: q_model for target and distribution_model for the main network.

**Comment by AlexKuhnle** [comment]
I see, haven't thought about that, sounds reasonable. We hope that with the next big version we have a more principled approach to these things, but that is probably a few months away... experience tells us. :-)

Yes, that's true. Although there are various places where such a modularization is possible (hence my thinking about 'inconsistency'), I guess there is no point not taking first steps towards it where it turns out necessary. I will merge it then, but will still get rid of the static flags -- although not necessary, I find non-static clearer in terms of procedural flow.

Thanks for all this, very appreciated! :+1:

**Comment by AlexKuhnle** [comment]
Hmm, I can't 'rebase and merge' due to conflicts... Wanna get rid of them before, or shall I fix them?

**Pull request merged**
