### PR TITLE
Cleanup and decomposition of model.py:setup() in preparation of "distributed/execution"-project(s)

### PR DESCRIPTION
**Pull request by sven1977**
Minor refactoring for the model.py:setup() method.
Cleaned it up a little and broke it down into smaller, more comprehensive chunks:
- init graph
- start server
- build graph
- saver
- summaries
- scaffold
- session-hooks
- session

Added sanity checkers and pre-processors for some spec-dicts (state, action, execution) to contrib/sanity_check_specs.py. This is to keep spec-logic and sanity checking in one place. Other specs can be added.

This is in preparation of the upcoming execution/distributed RL changes.

Test are all pass.

Next, I'll go through running a distributed DQN agent (bundled mode) and see what needs to be done with the memories for making distributed work. But maybe it's already ok.

Then I'll add more and more distributed/execution options.

### CODE REVIEW

**Comment by michaelschaarschmidt** [comment]
Liking the re-organisation, small nit:
graph_default_ctx <- We typically to write out these things, I assume it means context?

**Comment by sven1977** [comment]
Yup. It's the with self.graph.as_default (): Context.

**Comment by sven1977** [comment]
Changed it and added a couple more fixes and comments.

**Comment by michaelschaarschmidt** [comment]
Looks good now, ready to merge?

**Comment by sven1977** [comment]
All good with me. Tests are still pass (after the changes I made).

**Comment by sven1977** [comment]
One sec! TestModelSaveRestore is currently failing. I'm checking ...

**Comment by sven1977** [comment]
All good. Was just my local tf-debug-code. Please go ahead.

**Comment by michaelschaarschmidt** [comment]
Had already gone ahead : p

**Comment by sven1977** [comment]
Great. Thanks!

**Comment by sven1977** [comment]
Oh, yeah. Didn't see that merge item way above in this thread here. :)

**Pull request merged**
