### PR TITLE
An implementation of KFac Optimization compatible with tensorforce

### LINKED ISSUE #183: Implement KFAC-optimizer
Necessary for ACKTR but would also be available for other models via the new optimizers.

### PR DESCRIPTION
**Pull request by daggertye**
Closes #183

### CODE REVIEW

**Comment by AlexKuhnle** [comment]
hey @daggertye, that sounds really cool! Have you experimented with it already? I scrolled over it and found one likely tpo in line 926 regarding `var` and `vars`. Apart from that, and assuming you did some testing, I'm happy to merge. Great work!

**Comment by AlexKuhnle** [comment]
Could you run some basic checks whether it learns something?

**Comment by daggertye** [comment]
I ran it on a couple of networks and it was optimizing the loss, as desired.

**Comment by AlexKuhnle** [comment]
Cool, I assume that we can merge then. Thanks for the great work!

**Pull request merged**
