### PR TITLE
Unify Runner classes via BaseRunner parent class

### PR DESCRIPTION
**Pull request by sven1977**
Introduced BaseRunner class.
Restructured existing Runner classes (Runner and ThreadedRunner) to both inherit from BaseRunner.
Unified the interfaces used to control these classes and to handle per-episode and per-n-episode reporting.
Added multi-threaded testing to random and constant agent tests (configurable for all agents via run_type flag).
Removed some tf deprecation WARNINGS.

### CODE REVIEW

**Comment by michaelschaarschmidt** [comment]
Looking good to me, could argue whether we should use multi threaded on an agent that is actually learning (vs random agent), but mergable. Don't know why rebasing does not work.
Any comments @AlexKuhnle ?

**Comment by sven1977** [comment]
Ok, thanks guys!
I was trying to avoid adding more load to Travis (as Michael hinted in the gitter dev board). I will revert the 2 non-learning-agent tests as were (single mode) and add a new multi-threaded test case for PPO. Is there anything we can do about Travis accepting larger test loads? Like a paid account?

**Comment by AlexKuhnle** [comment]
I think the tests recently take only something like 10-15min, and the limit is 45min or so (right, @michaelschaarschmidt ?), so that should be fine... (or I get something wrong with what kind of load was talked about^^).

**Comment by michaelschaarschmidt** [comment]
I think there is a general travis issue where our tests terminate early, see recent builds, and it's unclear what exactly causes this (individual tests stalling/taking too many resources/build error from gym version)

**Comment by sven1977** [comment]
Please hold on. Still testing PPO + multithreaded.
...

**Comment by sven1977** [comment]
Ok, added another bug fix to multi-threaded functionality. All good now.
Added the multi-threaded run to the PPO agent. Each agent can now be configured via a bitfield to run in single, multi-threaded or both.

**Comment by michaelschaarschmidt** [comment]
Does this mean we are ready to merge? We should merge this before merging memory in any case? @AlexKuhnle

**Comment by sven1977** [comment]
My local tests were all ok. Not sure about travis. There seem to be new problems with openAI spaces and others. When I have some time, I'll take a look at this topic and try to stabilize the automatic tests.

**Comment by michaelschaarschmidt** [comment]
I will merge this now but may make some changes on the tests (re: runmode), also in preparation for merging memory, because this definitely needs to be merged before, thanks!

**Comment by sven1977** [comment]
Thanks Michael!

**Pull request merged**
