### PR TITLE
Unreal Engine 4 Support

### PR DESCRIPTION
**Pull request by sven1977**
Added Support for Unreal Engine 4-based Environment instances to TensorForce.
UE4 Envs can either be run in the UE4 editor (rendered/simulated/"watching" mode) or run headlessly on Linux (parallelized/"real" mode).
A UE4 Plugin ("Engine2Learn") is needed from github.com/ducandu/engine2learn repo in order to convert a UE4 game into a reinforcement learnable environment.

### CODE REVIEW

**Comment by michaelschaarschmidt** [comment]
Hey, a few more comments:
So this is definitely our fault and adding a style file is one the long to do list, but a few more style things to get more adjusted to our style:
- Line comments ideally capitalised, especially if they are actual sentences such as '# wait for an immediate response'
- For commenting style, you can select the 'google style' in Pycharm to get our style
- Line comments ideally also above the line referenced, which tends to make for shorter lines:
``` self.buffer_size = 8192  # the size of the response buffer (depends on the Env's observation-space)```
->
```
# The size of ..
self.buffer_size = 8192 
```

**Comment by sven1977** [comment]
Great. Thanks Michael. Will adjust my code/comment style for future PRs to match these guide lines.

**Comment by michaelschaarschmidt** [comment]
Great, thanks, merged

**Comment by sven1977** [comment]
Awesome. Thanks Michael!

**Pull request merged**
