### PR TITLE
Added possibility to specify tensorflow session config for all session types not only distributed

### PR DESCRIPTION
**Pull request by philipshurpik**
Hi!

Thanks for your project.
I started using your project but found that I'm unable to specify tensorflow session config when doing not distributed training.

I found that it was done before in https://github.com/reinforceio/tensorforce/pull/237
But unfortunately now this code does not exist, and it's impossible to set session_config from outside of the library.

Also, I moved session_config from the distributed spec because it's not only distributed functionality (and to not duplicate it in arguments)

### CODE REVIEW

**Comment by michaelschaarschmidt** [comment]
Hm,
should this not then also be part of the agent API? I think long-term I would make this part of an execution config dict handling these aspects, but for now it could be either part of distributed spec or a separate agent constructor parameter. I agree it's not distributed specific.

**Comment by michaelschaarschmidt** [comment]
Have begun to do execution refactoring to have a high level execution config, session config is now part of that so that addresses your issue

**Comment by philipshurpik** [comment]
thanks!

**Comment by michaelschaarschmidt** [comment]
Closing then

**Pull request closed without merging**
