### PR TITLE
Further cleanup of model.py:setup().

### PR DESCRIPTION
**Pull request by sven1977**
Major refactor in model.py.initialize: Split, renamed and further packaging of sub-tasks by the model's setup function. This will make it easier to write sub-classes for `Model`. Added some missing doc-strings. 
Moved global counters into a cleaner tf.get_variable-logic (instead tf.Variable).

Slight Memory-classes refactor. Moved tf function creation into its own setup function called by init.

Optimizers: Some commenting, removed get_wrapper (replaced by functools.partial).

### CODE REVIEW

**Comment by michaelschaarschmidt** [comment]
What is the reasoning for 

'''-    def tf_step(self, time, variables, global_variables, **kwargs):'''

removing global_variables as an explicit argument?

**Comment by sven1977** [comment]
Pycharm complained that the signature did not match the parent's signature (see: Liskov substitution principle):

"Signature of method 'SomeClass.func()' does not match signature of base method in class 'SomeClass' less... (Ctrl+F1) 
This inspection detects inconsistencies in overriding method signatures."

**Comment by michaelschaarschmidt** [comment]
No that makes sense, and I agree listening to Pycharm warnings is usually a very good idea

**Comment by sven1977** [comment]
Ok, cool.
However, again, in this case we are violating Liskov substitution principle either way, due the global_variables being enforced. :|

**Comment by sven1977** [comment]
Thanks Michael!

**Pull request merged**
