### PR TITLE
summary_spec description

### PR DESCRIPTION
**Pull request by Mazecreator**
Add summary_spec description in Markdown format

### CODE REVIEW

**Comment by michaelschaarschmidt** [comment]
thanks! I might move it into a manuals folder where we can collect these

**Comment by Mazecreator** [comment]
Sounds good, I just wanted to capture the information before it got forgotten.  I didn't know how to add it to the Docs.  Read the website but still couldn't figure out how to link it there... We should get one of these for Network_Spec too...

**Comment by michaelschaarschmidt** [comment]
I think the website docs are auto-generated, which is @krfricke territory (ask in gitter)

**Comment by krfricke** [comment]
We should move such file into the docs, either as a subchapter in the docs/agents_models.md file, or as a separate file. For networks it might make sense to add a neural_networks.md file or alike.
Anyway, such information belongs in the docs, otherwise the project root will be flooded. I'll move it to an appropriate location sometime this or next week.

**Pull request merged**
