### PR TITLE
SummarySessionWrapper to reduce Tensorboard tf.summary logging overhead

### PR DESCRIPTION
**Pull request by trickmeyer**
The previous workflow for Tensorboard logging was:

1. Check if the model should log
2. If so, append the summaries to fetches
3. Call session.run()
4. If should log, grab the summary results from session.run(), log them, and update the last log step.

SummarySessionWrapper makes this all transparent to the user with a simple interface:

`
with SummarySessionWrapper(self, fetches, feed_dict) as session:
    returns = session.run()
`

Behind the scenes, it checks to see if the model should log, and if so, tags on model.tf_summaries, which are set up when the instance is created.  when SummarySessionWrapper.run() is called, it only returns the original fetches, and hangs on to the tf_summaries for itself.  They are written on `__exit__`, and the last logged index is updated.  

This is also a step in the right direction for #146.

This has been implemented for the Model base class and PPOModel.  I can get to others upon request, otherwise will as I spend more time with them.

### CODE REVIEW

**Comment by trickmeyer** [comment]
one minor update needs to be done to not create red herrings when exceptions are raised during the run() method:

`
    def __exit__(self, exc_type, exc_val, exc_tb):
        if exc_tb is None:
            if not self._have_executed:
                raise TensorForceError('{} exiting without run() being called.'.format(self.__class__.__name__))
            if self._should_write_summaries:
                self._model.write_summaries(self._returns[-1])
                self._model.last_summary_step = self._model.timestep
        else:
            return 0
`

**Comment by AlexKuhnle** [comment]
Thanks, @trickmeyer, that sounds very useful, and potentially easier to integrate into the new version. We will come back to you.

**Comment by trickmeyer** [comment]
I went ahead and committed the change that will pass through exceptions encountered during session.run()

**Comment by trickmeyer** [comment]
This can only be used on graph runs where all summary variables are calculated.  If specific summary nodes aren't activated in a particular run this will fail.  We could handle this with a try/except, but it seems like a waste.  Probably worthy of pairing the correct run fetch/feed.

**Comment by AlexKuhnle** [comment]
We moved to using the TensorFlow `Supervisor` class in the new branch for session handling ([see here](https://github.com/reinforceio/tensorforce/blob/dev/tensorforce/models/model.py#L206)), and realized that it seems to implement exactly the functionality of your proposed `SummarySessionWrapper`. I'm not sure whether using `Supervisor` might be 'too much' in some cases, we have to investigate that...

**Comment by michaelschaarschmidt** [comment]
Ok this might have to be closed, summary handling is just handled entirely different now.

**Comment by trickmeyer** [comment]
You got it.

**Comment by michaelschaarschmidt** [comment]
Sorry for the extra work

**Comment by trickmeyer** [comment]
@michaelschaarschmidt none at all.

**Pull request closed without merging**
